final videosinfo = [
  {
    "title" : "Why Hitler Never Had an Atomic Bomb",
    "channel" : "Isam Ali",
    "views" : "1.3M views",
    "date" : "2 years ago",
    "pfp" : "assets/pfp/chosopfp.jpeg",
    "thumbnail" : "assets/thumbnail/thumbnail4.jpeg",
  },
  {
    "title" : "Bloodiest Day of World War 2 || D-Day (Minute by Minute)",
    "channel" : "Pirate Hunter",
    "views" : "1.2M views",
    "date" : "3 years ago",
    "pfp" : "assets/pfp/pirate.jpg",
    "thumbnail" : "assets/thumbnail/thumbnail7.jpeg",
  },
  {
    "title" : "Apollo 13 Space Mission Disaster (Hour by Hour)",
    "channel" : "Sky",
    "views" : "1.4M views",
    "date" : "2 years ago",
    "pfp" : "assets/pfp/sky.webp",
    "thumbnail" : "assets/thumbnail/thumbnail2.jpeg",
  },
  {
    "title" : "It's Not Just You. Nobody Likes Burger King Anymore.",
    "channel" : "Sycber",
    "views" : "419K views",
    "date" : "2 weeks ago",
    "pfp" : "assets/pfp/sycber.webp",
    "thumbnail" : "assets/thumbnail/thumbnail3.jpeg",
  },
  {
    "title" : "What If a Massive Asteroid Was Headed Towards Earth",
    "channel" : "Oni",
    "views" : "2.1M views",
    "date" : "2 years ago",
    "pfp" : "assets/pfp/oni.jpg",
    "thumbnail" : "assets/thumbnail/thumbnail6.jpeg",
  },
  {
    "title" : "Shocking Manhunt for the Mastermind of the Holocaust",
    "channel" : "The Infographics Show",
    "views" : "688K views",
    "date" : "1 year ago",
    "pfp" : "assets/pfp/infographics.jpg",
    "thumbnail" : "assets/thumbnail/thumbnail5.jpeg",
  },
  {
    "title" : "What if Hitler Never Invaded Russia",
    "channel" : "The Infographics Show",
    "views" : "213k views",
    "date" : "1 week ago",
    "pfp" : "assets/pfp/infographics.jpg",
    "thumbnail" : "assets/thumbnail/thumbnail1.jpeg",
  },
];